#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  AutoGentoo
#  
#  Copyright 2015 Andrei Tumbar <atadmin@Kronos>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

import os, sys

os.chdir(os.path.dirname(__file__))
sys.path.append(".")

from AutoGentoo import *
print ("""
 ______              __                 ____                       __                        
/\  _  \            /\ \__             /\  _`\_                   /\ \__                     
\ \ \_\ \    __  __ \ \  _\     ___    \ \ \_\_\     __     ___   \ \  _\     ___     ___    
 \ \  __ \  /\ \/\ \ \ \ \/    / __`\   \ \ \  __  /'__`\  /  _ `\ \ \ \/    / __`\  / __`\  
  \ \ \/\ \ \ \ \_\ \ \ \ \_  /\ \_\ \   \ \ \/  \/\ \/_/  /\ \/\ \ \ \ \_  /\ \_\ \/\ \_\ \ 
   \ \_\ \_\ \ \____/  \ \__\ \ \____/    \ \____/\ \____\ \ \_\ \_\ \ \__\ \ \____/\ \____/ 
    \/_/\/_/  \/___/    \/__/  \/___/      \/___/  \/____/  \/_/\/_/  \/__/  \/___/  \/___/  
""")
main()
