#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  AutoGentoo
#  
#  Copyright 2015 Andrei Tumbar <atadmin@Kronos>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
import os

class color:
	ESC_SEQ="\x1b["
	END=("%s39;49;00m" % (ESC_SEQ))
	RED=("%s31;01m" % (ESC_SEQ))
	GREEN=("%s32;01m" % (ESC_SEQ))
	YELLOW=("%s33;01m" % (ESC_SEQ))
	BLUE=("%s34;01m" % (ESC_SEQ))
	MAGENTA=("%s35;01m" % (ESC_SEQ))
	CYAN=("%s36;01m" % (ESC_SEQ))
	BOLD=("\033[1m")

os.chdir("/usr/lib/autogentoo")
from AutoGentoo import *
print ("%sStarting AutoGentoo%s" % (color.BOLD, color.END))
main()
