#!/usr/bin/env python

"""

This script will rewrite make.conf
take current variables from host and overwrite the file

"""

from client import Host


def script(_job_name: str, host: Host, _args=None):
	filename = host.get_path("etc/portage/make.conf")
	
	fp = open(filename, "w+")
	fp.write("""
# This file is automatically generated by the AutoGentoo service
# Contents changed here will be backed up in this directly
# To make persistant changes, edit this Host's config on autogentoo.org

# make.conf for {id},

# CFLAGS will be passed to every program compiled with GCC (almost everything).
# CFLAGS can be to optimize the runtime of the generated binaries
# NOTE: some CFLAGS may speed up the system on specific CPUs and not run on others
# Refer to https://wiki.gentoo.org/wiki/GCC_optimization for details on what to write here
# NEVER USE '-march=native' unless you are sure the compile server has the same cpu as the client
CFLAGS=\"{cflags}\"


# CXXFLAGS are the same as CFLAGS except passed only to C++ compiles
# Recommended: CXXFLAGS=\"${CFLAGS}\"
CXXFLAGS=\"{cxxflags}\"


# USE flags will add or remove certain features of installed packages
# The USE variable in this file will apply globally to every package
# To change a use flags for one package, use package.use
USE=\"{use}\"

# The following entries were appended by the user
""".format(**vars(host), CFLAGS="{CFLAGS}"))
	
	for key in host.extra:
		fp.write("%s=\"%s\"\n" % (key, host.extra[key]))
	
	fp.write("""
# The following should NOT be changed
# Build directory
PORTAGE_TMPDIR=\"{portage_tmpdir}\"
# ebuild portage tree (shared)
PORTDIR=\"{portdir}\"
# Distfile directory (shared)
DISTDIR=\"{distdir}\"
# Package binary directory
PKGDIR=\"{pkgdir}\"
# Build log directory
PORTAGE_LOGDIR=\"{portage_logdir}\"
# Log message language
LC_MESSAGES=\"{lc_messages}\"
""".format(**vars(host)))
