import enum

from .autogentoo_cportage import *


class UseOperatorT(enum.IntEnum):
    DISABLE = USE_OP_DISABLE
    ENABLE = USE_OP_ENABLE
    LEAST_ONE = USE_OP_LEAST_ONE
    EXACT_ONE = USE_OP_EXACT_ONE
    MOST_ONE = USE_OP_MOST_ONE


class UseStateT(enum.IntEnum):
    DISABLED = USE_STATE_DISABLED
    ENABLED = USE_STATE_ENABLED


class AtomUseT(enum.IntEnum):
    DISABLE = ATOM_USE_DISABLE
    ENABLE = ATOM_USE_ENABLE
    ENABLE_IF_ON = ATOM_USE_ENABLE_IF_ON
    DISABLE_IF_OFF = ATOM_USE_DISABLE_IF_OFF
    EQUAL = ATOM_USE_EQUAL
    OPPOSITE = ATOM_USE_OPPOSITE


class AtomUseDefaultT(enum.IntEnum):
    NONE = ATOM_DEFAULT_NONE
    ON = ATOM_DEFAULT_ON
    OFF = ATOM_DEFAULT_OFF


class AtomVersionT(enum.IntFlag):
    NONE = ATOM_VERSION_NONE
    E = ATOM_VERSION_E
    L = ATOM_VERSION_L
    G = ATOM_VERSION_G
    REV = ATOM_VERSION_REV
    ALL = ATOM_VERSION_ALL
    GE = ATOM_VERSION_GE
    LE = ATOM_VERSION_LE


class AtomBlockT(enum.IntEnum):
    NONE = ATOM_BLOCK_NONE
    SOFT = ATOM_BLOCK_SOFT
    HARD = ATOM_BLOCK_HARD


class AtomSlotT(enum.IntEnum):
    IGNORE = ATOM_SLOT_IGNORE
    REBUILD = ATOM_SLOT_REBUILD


class AtomVersionPreT(enum.IntEnum):
    ALPHA = ATOM_PREFIX_ALPHA
    BETA = ATOM_PREFIX_ALPHA
    PRE = ATOM_PREFIX_ALPHA
    RC = ATOM_PREFIX_ALPHA
    NONE = ATOM_PREFIX_ALPHA
    P = ATOM_PREFIX_ALPHA


class ArchT(enum.IntEnum):
    ARCH_AMD64 = ARCH_AMD64
    ARCH_X86 = ARCH_X86
    ARCH_ARM = ARCH_ARM
    ARCH_ARM64 = ARCH_ARM64
    ARCH_HPPA = ARCH_HPPA
    ARCH_IA64 = ARCH_IA64
    ARCH_PPC = ARCH_PPC
    ARCH_PPC64 = ARCH_PPC64
    ARCH_SPARC = ARCH_SPARC
    ARCH_END = ARCH_END


class KeywordT(enum.IntEnum):
    KEYWORD_BROKEN = KEYWORD_BROKEN
    KEYWORD_NONE = KEYWORD_NONE
    KEYWORD_UNSTABLE = KEYWORD_UNSTABLE
    KEYWORD_STABLE = KEYWORD_STABLE
