from typing import Union, Callable


class TCPServer:
    def __init__(self, address: Union[str, int]): ...

    def start(self): ...

    def stop(self): ...

    def set_request_callback(self, callback: Callable[[tuple], None]): ...
