from typing import Union, Callable, Tuple


class TCPServer:
    def __init__(self, address: Union[str, int]): ...

    def start(self): ...

    def stop(self): ...

    def set_request_callback(self, callback: Callable[[tuple], None]): ...


def send_message(address: Union[Tuple[int, int], str]) -> tuple :...
